services:
  # para autenticação (armazenamento de usuarios)

  mongo:
    build: 
      context: ./auth
      dockerfile: Dockerfile.mongo
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  authentication:
    build: 
      context: ./auth
      dockerfile: Dockerfile.node
    container_name: auth_container
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      
volumes:
  mongo_data:
