services:
  # para autenticação (armazenamento de usuarios)
  mongodb:
    build: 
      context: ./auth
      dockerfile: Dockerfile.mongo
    container_name: mongo_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db


  authentication:
    build: 
      context: ./auth
      dockerfile: Dockerfile.node
    container_name: auth_container
    ports:
      - "3000:3000"

    depends_on:
      - mongodb
      
volumes:
  mongo_data:
