services:
  # para autenticação (armazenamento de usuarios)
  mongodb:
    build: 
      context: ./auth
      dockerfile: Dockerfile.mongo
    container_name: mongo_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/data/db
    networks:
      - project_network

  authentication:
    build: 
      context: ./auth
      dockerfile: Dockerfile.node
    container_name: auth_container
    ports:
      - "3000:3000"
    networks:
      - project_network
    volumes:
      - ./auth:/app
    depends_on:
      - mongodb
      
volumes:
  mongo_data:

networks:
  project_network:
    driver: bridge