services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
  django:
    container_name: django
    environment:
      DJANGO_HOST_PORT: ${DJANGO_HOST_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    restart: always
    build:
      context: ./django 
    volumes:
      - ./django:/code
      - ./django/media:/code/media
    ports:
      - ${DJANGO_HOST_PORT}:${DJANGO_HOST_PORT}
    depends_on:
      - db

volumes:
  pgdata: