services:

  db:
    container_name: db
    image: postgres:16.4-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - '15672:15672'
    depends_on:
      - db

  celery_worker: 
    container_name: celery_worker
    environment:
      DEBUG: "True"
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_HOST: rabbitmq  # serviço do rabbitmq acima
    restart: always
    build:
      context: ./django
    command: >
      sh -c "
        celery -A app worker -l info
      "
    ports:
      - 6900:6900
    volumes:
      - ./django:/code
    depends_on:
      - rabbitmq

  django:
    container_name: django
    environment:
      DJANGO_HOST_PORT: ${DJANGO_HOST_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_HOST: db  # serviço do postgres acima
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_HOST: rabbitmq  # serviço do rabbitmq acima
    restart: always
    build:
      context: ./django
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:${DJANGO_HOST_PORT}
      "
    volumes:
      - ./django:/code
      - ./django/media:/code/media
    ports:
      - ${DJANGO_HOST_PORT}:${DJANGO_HOST_PORT}
    depends_on:
      - db
      - rabbitmq

  fastapi:
    container_name: fastapi
    build: ./pdf_to_image
    environment:
      FASTAPI_PORT: ${FASTAPI_PORT}
    ports:
      - ${FASTAPI_PORT}:${FASTAPI_PORT}
    volumes:
      - ./pdf_to_image:/code
      - ./pdf_to_image/uploads:/code/uploads
    command: >
      sh -c "
        uvicorn app.main:app --host 0.0.0.0 --port ${FASTAPI_PORT}
      "

volumes:
  pgdata:
