services:

  db:
    image: postgres:16.4-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

  django:
    container_name: django
    environment:
      DJANGO_HOST_PORT: ${DJANGO_HOST_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_HOST: db # serviço do postgres acima
    restart: always
    build:
      context: ./django 
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:${DJANGO_HOST_PORT}
      "
    volumes:
      - ./django:/code
      - ./django/media:/code/media
    ports:
      - ${DJANGO_HOST_PORT}:${DJANGO_HOST_PORT}
    depends_on:
      - db

  fastapi:
    container_name: fastapi
    build: ./pdf_to_image
    ports:
      - 8000:8001

volumes:
  pgdata: